version: '3.8'

services:
  api:
    build:
      context: .
      args:
        - MONGODB_URI=${MONGODB_URI}
        - JWT_SECRET=${JWT_SECRET}
        - PORT=${PORT:-5555}
    ports:
      - "${PORT:-5555}:${PORT:-5555}"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT:-5555}
    restart: unless-stopped 